# Generated by Django 4.2.3 on 2023-07-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('credit_card', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('ssn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('size', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
